using ExpenseTracker.Api.Data;
using ExpenseTracker.Api.Dtos;
using ExpenseTracker.Api.Entities;
using ExpenseTracker.Api.Exceptions;
using Microsoft.EntityFrameworkCore;

namespace ExpenseTracker.Api.Services;

/// <summary>
/// Contract for the person service. The interface separates behavior from
/// implementation, easing testing and dependency injection.
/// </summary>
public interface IPersonService
{
    Task<PersonResponse> CreateAsync(CreatePersonRequest request, CancellationToken ct);
    Task<IReadOnlyList<PersonResponse>> ListAsync(CancellationToken ct);
    Task DeleteAsync(Guid id, CancellationToken ct);
}

/// <summary>
/// Person business rules: create, list and delete.
/// </summary>
public class PersonService : IPersonService
{
    private readonly AppDbContext _db;

    public PersonService(AppDbContext db)
    {
        _db = db;
    }

    public async Task<PersonResponse> CreateAsync(CreatePersonRequest request, CancellationToken ct)
    {
        // Build the entity from the DTO. The Guid Id is generated by EF Core.
        var person = new Person
        {
            Name = request.Name,
            Age = request.Age
        };

        _db.People.Add(person);
        // All database access is asynchronous to avoid blocking the thread.
        await _db.SaveChangesAsync(ct);

        return new PersonResponse(person.Id, person.Name, person.Age);
    }

    public async Task<IReadOnlyList<PersonResponse>> ListAsync(CancellationToken ct)
    {
        // AsNoTracking: read-only query without change tracking (faster).
        // Projected straight into the DTO with Select (LINQ is translated to SQL).
        return await _db.People
            .AsNoTracking()
            .OrderBy(p => p.Name)
            .Select(p => new PersonResponse(p.Id, p.Name, p.Age))
            .ToListAsync(ct);
    }

    public async Task DeleteAsync(Guid id, CancellationToken ct)
    {
        var person = await _db.People.FirstOrDefaultAsync(p => p.Id == id, ct);

        // Deleting a non-existent person returns 404 with a clear message.
        if (person is null)
        {
            throw new NotFoundException($"Pessoa com Id '{id}' não encontrada.");
        }

        // Business rule 1: removing the Person triggers the cascade delete
        // configured in AppDbContext, which automatically deletes all of their
        // transactions — no need to delete the transactions manually here.
        _db.People.Remove(person);
        await _db.SaveChangesAsync(ct);
    }
}
